### ISSUE TITLE
time.sleep(0.5) error

### ISSUE THREAD

**Issue by hzshang** [WangYihang/Reverse-Shell-Manager#3]
Reverse-Shell-Manager.py, 318行
`time.sleep(0.5)`
时间有点短，运行时经常出错

```
  File "Reverse-Shell-Manager.py", line 320, in main
    position = slaves[slaves.keys()[0]].node_hash  # master himself
IndexError: list index out of range
```
建议时间改长点

**Comment by WangYihang** [comment]
收到 , 这个问题之前我也发现了 , 但是之前一直没有找到如何复现 , 感谢提出 issue , 今天晚上有时间会修复
这个 bug 的原因在于对每一个上线的 slave 会通过淘宝的 api 获取地理位置 , 直接使用了 requests 这个库 , 是阻塞的 , 因此在网络情况比较差的时候就会出现这个 bug

**Comment by hzshang** [comment]
访问淘宝的时候可以try catch一下, 一般ctf线下赛都是在局域网，根本连不上外网的。
今天打比赛，就直接gg了。。
真是个悲伤的故事
```
Reverse-Shell-Manager$ py rsm.py 0.0.0.0 1234
[+] Starting server...
[+] Master starting at 0.0.0.0:1234
[+] Connecting to localhost server...
[+] Slave online : 127.0.0.1:62112
[-] SOCKSHTTPConnectionPool(host='ip.taobao.com', port=80): Max retries exceeded with url: /service/getIpInfo.php?ip=127.0.0.1 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x1021e2e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "rsm.py", line 260, in master
    slave = Slave(slave_fd)
  File "rsm.py", line 120, in __init__
    self.country = self.api_info['country']
KeyError: 'country'

```

**Comment by WangYihang** [comment]
是... 就是因为前几周的XDCTF我才搞清楚这个 BUG 的由来 , 当时整了好久才搞清楚为啥会有这个 BUG ...
Sorry 啊...

**Comment by WangYihang** [comment]
@hzshang 大佬是在上海吗 ? 怎么样呀 ?

**Comment by hzshang** [comment]
两道题，尴尬的是pwn题全场最后都没做出来
刚刚入门ctf，被别人吊打了一波。。。

**Comment by WangYihang** [comment]
简单修复了一下 , 应该暂时能解决这个问题 , 之后考虑使用异步 HTTP 库来处理 HTTP 请求 , 可能会用到 grequests
