### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JRWR** [WangYihang/Reverse-Shell-Manager#5]
```

/Reverse-Shell-Manager# python -V
Python 2.7.15rc1

root@:~/Reverse-Shell-Manager# python Reverse-Shell-Manager.py 0.0.0.0 80
[+] Starting server...
[+] Master starting at 0.0.0.0:80
[+] Connecting to localhost server...
[+] Slave online : 127.0.0.1:38734
Commands :
        0. [h|help|?|\n] : show this help
        1. [l] : list all online slaves
        2. [p] : log.info(position info
        3. [i] : interactive shell
        4. [g] : goto a slave
        5. [gf] : get flag
        6. [gaf] : get all flag
        7. [c] : command for all
        8. [cronadd] : add crontab
        9. [crondel] : del crontab
        10. [cl] : command to log
        11. [setl] : set local execute
        12. [setr] : set remote execute
        13. [d] : delete node
        14. [ac] : auto connection
        15. [aac] : all node auto connction
        16. [nm] : listen another port
        17. [q|quit|exit] : exit
Traceback (most recent call last):
  File "Reverse-Shell-Manager.py", line 470, in <module>
    main()
  File "Reverse-Shell-Manager.py", line 319, in main
    position = slaves[slaves.keys()[0]].node_hash  # master himself
IndexError: list index out of range
root@~/Reverse-Shell-Manager#





```

**Comment by WangYihang** [comment]
Thanks for reporting, I will fix it tomorrow
